name: Build and Push to ACR
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Logowanie do ACR
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Budowanie i wypchnięcie obrazu
      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest -f ./AlgoRhythm/Dockerfile ./AlgoRhythm
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest